#!/usr/bin/env python3
##
## EPITECH PROJECT, 2023
## B-MAT-200-STG-2-1-107transfer-titouan.pradoura
## File description:
## 107transfer
##

import sys

def analyse_char(str_func):
    function = []
    value = str_func.split('*')

    try:
        for i in range(len(value)):
            value[i] = float(value[i]);
    except:
        sys.exit(84);
    return value

def main():
    poly_list = []
    numerator = 0
    if len(sys.argv) < 2:
        sys.exit(84);
    for i in range (1, len(sys.argv), 1):
        poly_list.append(analyse_char(sys.argv[i]))
    for x in range(0, 1001, 1):
        value = None
        for equa in range(0, len(poly_list), 2):
            numerator = 0
            deno = 0
            for index in range(len(poly_list[equa])):
                numerator += poly_list[equa][index] * ((x / 1000) ** index)
            if (equa + 1 >= len(poly_list)):
                sys.exit(84)
            for index in range(len(poly_list[equa + 1])):
                deno += poly_list[equa + 1][index] * ((x / 1000) ** index)
            if deno == 0:
                sys.exit(84)
            if value != None:
                value *= numerator / deno
            else:
                value = numerator / deno
        print(f"{x/1000:.3f} -> {value:.5f}")
    sys.exit(0);
    
if __name__ == "__main__":
    main()